spring:
  profiles:
    active: test
    group:
      local: dev, common
      test: test, common

---
spring:
  config:
    activate:
      on-profile:
        - common
  application:
    name: going-project-v.1.0
  main:
    banner-mode: OFF
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    mode: HTML
    cache: false
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
      cache:
        period: 36000

mybatis:
  configuration:
    lazy-loading-enabled: true
    cache-enabled: false
    local-cache-scope: STATEMENT
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: NULL
  type-aliases-package: com.subin.gople.domain.**.dto
  type-handlers-package: com.subin.gople.global.common.mybatis
  mapper-locations:
    - classpath:mappers/*_mapper.xml

server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    url: jdbc:mariadb://localhost:3306/gople?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: suihin92
    password: tq3599
    driver-class-name: org.mariadb.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile:
        - test
  datasource:
    url: jdbc:h2:mem:gople;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
  sql:
    init:
      mode: EMBEDDED
      schema-locations:
        - classpath:sql/h2/schema.sql
      data-locations:
        - classpath:sql/h2/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true

logging:
  level:
    root: warn
    web: debug