#
# 스프링부트 애플리케이션 테스트 환경 설정
#


spring:
  config:
    activate:
      on-profile:
        - test
  # 테스트 환경을 위한 인메모리 데이터베이스(H2) 연결 정보 설정
  datasource:
    url: jdbc:h2:mem:gople;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    driver-class-name: org.h2.Driver
  # 테스트를 위한 데이터베이스는 DDL이력 및 스키마 버전 등을 관리할 필요가 없기 때문에 false로 변경
  flyway:
    enabled: false

  sql:
    init:
      # 모드 - ALWAYS: 모든 데이터베이스의 SQL 스크립트 동작, EMBEDDED: 내장 데이터베이스 SQL 스크립트만 동작, NEVER: SQL 스크립트 동작 X
      mode: EMBEDDED
      schema-locations:
        - classpath:sql/h2/schema.sql
      data-locations:
        - classpath:sql/h2/data.sql

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true

logging:
  level:
    root: warn
    web: debug

