#
# 스프링부트 애플리케이션 공통 환경 설정
#


spring:
  config:
    activate:
      on-profile:
        - common
  application:
    name: going-project-v.1.0
  main:
    banner-mode: off  # 런타임시 콘솔상에 출력되는 배너 끄기
  # 웹 브라우저의 새로고침을 통한 화면단의 변경 이력을 반영하기 위한 뷰단 파일 경로 및 캐시값 변경
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    cache: false  # 모든 개발이 완료된 후 true → false 변경
  # 웹 브라우저의 새로고침을 통한 화면단의 변경 이력을 반영하기 위한 정적 리소스 파일의 경로 변경 및 캐시 설정
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
      cache:
        period: 36000 # 리소스의 캐시 기간을 지정 → 캐시 시간 관련 응답 헤더를 전송


mybatis:
  # 런타임시 마이바티스의 동작 제어를 위한 설정 값 세팅
  configuration:
    lazy-loading-enabled: true          # 불필요한 정보의 로드를 사전에 방지하기 위한 지연로딩 설정 활성화
    cache-enabled: false                # 매퍼의 네임스페이스 단위로 동작되는 세컨드 레벨의 캐시 비활성화
    local-cache-scope: STATEMENT        # 로컬 캐시 적용 범위를 변경
    map-underscore-to-camel-case: true  # 스네이크케이스 표기법의 컬럼명을 카멜케이스 표기법의 필드명으로 매핑 처리 허용
    call-setters-on-nulls: true         # 컬럼 값이 NULL일 경우 컬럼 값의 누락 방지를 위한 put메소드 및 setter메소드 호출 허용
    jdbc-type-for-null: NULL            # 파라미터로 전달된 NULL값에 대해 DBMS의 타입 변환을 NULL 그대로 처리하도록 설정
  type-aliases-package: com.subin.gople.domain.**.dto
  type-handlers-package: com.subin.gople.global.common.mybatis
  mapper-locations:
    - classpath:mappers/**/*_mapper.xml
    - classpath:mappers/*_mapper.xml


server:
  # 내장 톰캣 서버의 포트 번호 변경
  port: 80
  servlet:
    # HTTP 요청 및 응답의 인코딩 설정
    encoding:
      charset: UTF-8
      enabled: true
      force: true